name: a_dokter_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  appbar_animated: 0.0.3
  crypto: ^3.0.3
  dio: 5.1.1
  gif_view: ^0.3.1
  dismissible_page: ^1.0.2
#  flutter_advanced_calendar: ^1.3.0
  # qr_code_scanner: ^1.0.1
  mobile_scanner: ^3.2.0
  # drop_down_list: 0.0.5
  text_scroll: ^0.2.0
  calendar_timeline: ^1.1.2
  dropdown_search: 5.0.6
  carousel_slider: ^4.1.1
  horizontal_week_calendar: ^0.0.10
  flutter_onboarding_screen: 2.0.2
  flutter_onboarding_slider: 1.0.9
  flutter_staggered_grid_view: 0.6.2
  flutter_svg: ^1.1.0
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+4
  intl: 0.18.1
  shimmer_animation: ^2.1.0
  search_page: ^2.3.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

